### ISSUE TITLE
Je ne peux pas clone | I can't clone.

### ISSUE THREAD

**Issue by gibran-mojica** [X-SLAYER/Website-Cloner#3]
![image](https://user-images.githubusercontent.com/99934881/154604584-dd4d5544-15e4-401a-89d4-c2099a7e11ab.png)

**Comment by gibran-mojica** [comment]
help me

**Comment by X-SLAYER** [comment]
check where did u locate the xNet file and load it in the references
![image](https://user-images.githubusercontent.com/22800380/154798776-f7a6abfb-96d3-4c1d-b624-27186e99563d.png)
